apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: shestera/scaletestapp:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "30Mi"
              cpu: "100m"